### ISSUE TITLE
Script Not Working on Microsoft Surface

### ISSUE THREAD

**Issue by FluidNets-DamianS** [MechDR/automatically-connect-to-a-wi-fi-network-when-in-safe-mode-with-networking#1]
I ran into this issue with a Surface yesterday.  I tested on mine and confirmed that the device is shown to have a problem:

Windows cannot initialize the device driver for this hardware. (Code 37)

The request is not supported.

**Comment by MechDR** [comment]
I've ran into this problem with an Intel card. Don't actually know if other manufacturers do the same thing with some of their networking products (Wi-Fi cards/adapters in particular), but, apparently, the drivers of this particular Intel card are not fully independent, meaning, they rely on something else (probably another driver or a service) in order to properly load.

What's the hardware ID of the device? I'll try and see if it's a service the card's drivers depend on, that's easily fixable. But if it's another driver, not related to networking... I can't promise I can fix that. It's not related to the script itself, this is hardware/driver related. Still, I'll try my best.

**Comment by FluidNets-DamianS** [comment]
This is the Surface Book 1 below.  The Suface GO has ID 003E
[cid:image002.jpg@01D69FD8.B720F0F0]

Damian C. Stalls<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>
vCIO Director<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>
805.864.3620 Direct<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>
Schedule Meeting<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>

**Comment by MechDR** [comment]
Looks like the attachment didn't make it in the email, LOL :D. Could you reply directly on GitHub and attach the image that way? Oh, and could you also make a screenshot of the hardware IDs of the card?

**Comment by MechDR** [comment]
Issue closed due to inactivity and not enough info on the problem.
